INSERT INTO church_branches (name) VALUES
  ('Royalhouse, CT | Victory Center'),
  ('Royalhouse, DC | DC Mission'),
  ('Royalhouse DE | Delaware Fellowship'),
  ('Royalhouse, ATL | Miracle Life Center'),
  ('Royalhouse, MA | Mt. Zion Center'),
  ('Royalhouse, MD | Frederick Campus'),
  ('Royalhouse MD | Grace2Grace Center'),
  ('Royalhouse, NC | Bread of Life Center'),
  ('Royalhouse, NC | Dunamis Center'),
  ('Royalhouse, NC | Glory Center'),
  ('Royalhouse, NJ | Covenant Center'),
  ('Royalhouse, NY | Buffalo Fellowship'),
  ('Royalhouse, NY | Kingdom Center'),
  ('Royalhouse, NY | Latter Rain Center'),
  ('Royalhouse, PA | Philadelphia Mission'),
  ('Royalhouse, PA | Pittsburg Mission'),
  ('Royalhouse, TX | Houston Mission'),
  ('Royalhouse, VA | Breakthrough Center'),
  ('Royalhouse, VA | Norfolk Mission'),
  ('Royalhouse, WA | Washington Fellowship'),
  ('Royalhouse Canada | Canada Fellowship'),
  ('Royalhouse, NY | Orange & Rockland Fellowship');
