export const PAYMENT_URGENCY_HOURS = 24;
export const MAGIC_LINK_EXPIRY_MINUTES = 10;
export const RESEND_COOLDOWN_SECONDS = 60;
export const MIN_PAYMENT_AMOUNT = 2500;
export const CHILDREN_SURCHARGE_MULTIPLIER = 1;
